prevent commiting package-lock.json

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -2,3 +2,11 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npx lint-staged
+
+if git diff --name-only --cached | grep -q 'package-lock.json'; then
+  echo "Error: Make sure you doesn't not commit package-lock.json."
+  exit 1
+else
+  echo "Checked successfully."
+  exit 0
+fi
